export const APPRoutes = {
    LOGIN: "/",
    FORGOT_PASSWORD: "/forgot-password",
    RESET_PASSWORD: "/reset-password",
    VALIDATION_EXPIRES: "/validation-expires",
    DASHBOARD: "/dashboard",
    CLIENTS: "/clients",
    SUBSCRIPTION_MANAGE_PLANS: "/subscription/manageplans",
    SUBSCRIPTION_SUBSCRIBERS: "/subscription/subscribers",
    SUBSCRIPTION_SUBSCRIBER_VIEW: "/subscription/subscribers/view/:id",
    SUBSCRIPTION_CREATE: "/subscription/create",
    SUBSCRIPTION_EDIT: "/subscription/edit/:id",
    SUBSCRIPTION_VIEW: "/subscription/view/:id",
    RESTRICTED: "/restricted",
    CLIENTS_FORM: "/clients/form",
    CLIENTS_EDIT: "/clients/edit/:id",
    CLIENTS_VIEW: "/clients/view/:id",
    AUDIT_LOGS: "/audit-logs",
    AUDIT_LOGS_VIEW: "/audit-logs/view/:id",
    ROLES: "/roles",
    ROLES_FORM: "/roles/form",
    ROLES_EDIT: "/roles/edit/:id",
    ROLES_VIEW: "/roles/view/:id",
    USERS: "/users",
    USERS_FORM: "/users/form",
    USERS_EDIT: "/users/edit/:id",
    USERS_VIEW: "/users/view/:id",
    DOCTORS: "/doctors",
    DOCTORS_VIEW: "/doctors/view/:id",
    DOCTORS_SCHEDULE: "/doctors/schedule/:id",
    SERVICES: "/services",
    SERVICES_VIEW: "/services/view/:id",
}

